#!/usr/bin/env python3
"""Generate Go advisory DB from reviewed JSON.

Runtime scanner stays offline. This script runs in CI/maintenance to compile the
reviewed JSON database into ordinary Go data.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "internal/rules/builtin/advisories/agent-packages.json"
OUT_PATH = ROOT / "internal/rules/builtin/dependencies_db_generated.go"

SEVERITY = {
    "critical": "finding.SeverityCritical",
    "high": "finding.SeverityHigh",
    "medium": "finding.SeverityMedium",
    "low": "finding.SeverityLow",
}


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def go_tags(tags: list[str]) -> str:
    if not tags:
        return "nil"
    return "[]string{" + ", ".join(q(t) for t in tags) + "}"


def main() -> None:
    db = json.loads(DB_PATH.read_text())
    advisories = sorted(
        db.get("advisories", []),
        key=lambda a: (a.get("ecosystem", ""), a.get("package", ""), a.get("cve", "")),
    )
    lines = [
        "// Code generated by scripts/generate-agent-package-advisories.py; DO NOT EDIT.",
        "package builtin",
        "",
        "import \"github.com/harshmaur/audr/internal/finding\"",
        "",
        "var dependencyAdvisories = []dependencyAdvisory{",
    ]
    for a in advisories:
        sev = SEVERITY.get(a.get("severity", "high"))
        if not sev:
            raise SystemExit(f"unknown severity for {a.get('cve')}: {a.get('severity')}")
        lines.extend(
            [
                "\t{",
                f"\t\tEcosystem: {q(a['ecosystem'])}, Package: {q(a['package'])}, CVE: {q(a['cve'])},",
                f"\t\tTitle: {q(a['title'])},",
                f"\t\tSeverity: {sev}, FixedVersion: {q(a.get('fixed_version', ''))}, LastVulnerable: {q(a.get('last_vulnerable', ''))}, ExactVersion: {q(a.get('exact_version', ''))}, MinVersion: {q(a.get('min_version', ''))},",
                f"\t\tTags: {go_tags(a.get('tags', []))},",
                "\t},",
            ]
        )
    lines.append("}")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {OUT_PATH.relative_to(ROOT)} with {len(advisories)} advisories")


if __name__ == "__main__":
    main()
